add Type Map , Add  Log , Add  stripStart,Add Size and Precision
hebaoning/sqoop pull request #1
Opened 2018-05-08 13:51 UTC by henrryChen1

2018-05-08 14:15 UTC, hebaoning requested changes

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> -        columnTypes = connManager.getColumnTypesForQuery(options.getSqlQuery());
为啥删掉？

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/orm/ClassWriter.java
> +        sb.append("    this." + col + " = StringUtils.strip(JdbcWritableBridge." +  getterMethod
前置空格可以随便删除吗

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> +    LOG.info("Create statement: " + sb.toString());
删

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> +      if (HiveTypes.isHiveTypeImprovised(colType)&&("double".equals(StringUtils.trim(hiveColType))
为什么不在toHiveType里直接把DECIMAL，NUMBERIC转成Decimal？

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> +    LOG.info(columnTypes.toString());
删，或用debug

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/manager/SqlManager.java
> +  public Map<String, List<Integer>> getColumnTypesWithSizeAndprecision(String tableName) {
删，用getColumnInfo

2018-05-08 14:15 UTC, hebaoning commented on src/java/org/apache/sqoop/manager/ConnManager.java
> +  /**
删，已经有getColumnInfo了

2018-05-08 14:20 UTC, henrryChen1 commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> -        columnTypes = connManager.getColumnTypesForQuery(options.getSqlQuery());
这里方法返回值类型与 columTypes类型不同 且getColumnTypeForQuery 就是做一个验证的功能.如果是Null就直接返回Null.

2018-05-08 14:21 UTC, henrryChen1 commented on src/java/org/apache/sqoop/orm/ClassWriter.java
> +        sb.append("    this." + col + " = StringUtils.strip(JdbcWritableBridge." +  getterMethod
这个明天再和龙海确认一下他们之前和我说是要都删掉的。。。

2018-05-09 07:35 UTC, hebaoning requested changes

2018-05-09 07:35 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> +      if ("DECIMAL".equals(hiveColType)){
equalsIgnoreCase

2018-05-09 07:35 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/HiveTypes.java
>            case Types.NVARCHAR:
再完善下toHiveType
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-Date/TimeTypes

2018-05-09 07:35 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> -        columnTypes = connManager.getColumnTypesForQuery(options.getSqlQuery());
这个最后调用的是SqlManager的getColumnTypesForQuery…… 不是ConnManager的

2018-05-09 07:35 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
> +        int precision = columnTypes.get(col).get(1);
考虑DB2的Decimal类型没有定义precision和scale的情况

2018-05-09 07:35 UTC, hebaoning commented on src/java/org/apache/sqoop/orm/ClassWriter.java
> +        sb.append("    this." + col + " = StringUtils.strip(JdbcWritableBridge." +  getterMethod
能删掉吗

2018-05-12 04:21 UTC, hebaoning commented on src/java/org/apache/sqoop/hive/TableDefWriter.java
>        if (HiveTypes.isHiveTypeImprovised(colType)) {
isHiveTypeImprovised再改下

2018-05-12 04:39 UTC, merged